server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: recipe-api
  profiles:
    default: dev
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss