spring:
  datasource:
    url: jdbc:h2:mem:recipe_acc
    username: sa
    maximum-pool-size: ##max pool size
    maximum-idle: ##max idle
management:
  endpoints:
    web:
      exposure:
        include: 'info,health,metrics'
